### ISSUE TITLE
Food_court name issue

### ISSUE THREAD

**Issue by binoybarnabas** [whiskerandoes/ffc#1]
the project only works when the root repository is named as ffc. otherwise u have to change the directory reference accross all the code files on the current project or just change the root repository name to ffc.

**Comment by whiskerandoes** [comment]
> the project only works when the root repository is named as ffc. otherwise u have to change the directory reference accross all the code files on the current project or just change the root repository name to ffc.l

**Comment by s-u-r-y-a-s** [comment]
@binoybarnabas issue solved
